### ISSUE TITLE
Move this repo to Organisation

### ISSUE THREAD

**Issue by gbelanger** [volodymyrss/integral-isgri-rate-meaning#9]
Tried to push update to README but failed:
```
(base) gbelanger@My-MacBook-Pro integral-isgri-rate-meaning % git push origin low-energy-threshold 
ERROR: Permission to volodymyrss/integral-isgri-rate-meaning.git denied to gbelanger.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

Solution:
- Move repo to INTEGRAL Organisation
- Make sure permission as set to me to be able  to push.

**Comment by volodymyrss** [comment]
Ok, sorry I did not see! Please feel free to assign to me if possible. Maybe it was not.

**Comment by volodymyrss** [comment]
this Organization? Please have a look how it looks like now.

**Comment by gbelanger** [comment]
All good! Submitted changes [here](https://github.com/integral-observatory/integral-isgri-rate-meaning/pull/10)
